### ISSUE TITLE
CRAN Issue

### ISSUE THREAD

**Issue by GuerraSa** [warint/statcanR#2]
I'm getting the following error when I run `statcan_search`. It also looks like the package was removed from CRAN.

`No tables with this combination of keywords
Error in apply(statcandata, 1, function(row) {: object 'statcandata' not found`

**Comment by warint** [comment]
Hi,

statcan_search should work know, our server was down yesterday, sorry! It should be back on CRAN soon.

Thanks

**Comment by warint** [comment]
It's now back on CRAN.

Hope everything is working smoothly for you, otherwise, let us know.

Thanks

**Comment by warint** [comment]
issue closed
